# Generated by Django 4.0.3 on 2022-03-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peticioneslibro',
            options={'ordering': ['devolucion']},
        ),
        migrations.RenameField(
            model_name='peticioneslibro',
            old_name='retorno',
            new_name='devolucion',
        ),
    ]
