# Generated by Django 4.0.3 on 2022-03-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_peticioneslibro_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='fecha_nacimiento',
            new_name='fecha_de_nacimiento',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='fecha_deceso',
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_de_deceso',
            field=models.DateField(blank=True, null=True, verbose_name='Deceso'),
        ),
    ]
