# Generated by Django 4.0.3 on 2022-03-23 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_rename_fecha_nacimiento_autor_fecha_de_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='idioma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.idioma'),
        ),
    ]
