# Generated by Django 4.0.3 on 2022-03-31 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_autor_options_peticioneslibro_prestatario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peticioneslibro',
            options={'ordering': ['devolucion'], 'permissions': (('can_mark_returned', 'Establece libro como regresado'),)},
        ),
    ]
